recipes_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from web.views import home_view, registration_view, auth_view, logout_view, add_recipe_view, IngredientSearchView, \
    recipes_view, RecipeDetailView, LikeRecipeView, analytics_view, import_view, stat_view

urlpatterns = [
    path('', home_view, name='home'),
    path('sign_up/', registration_view, name='sign_up'),
    path("sign_in/", auth_view, name="sign_in"),
    path("sign_out/", logout_view, name="sign_out"),
    path("recipes/", recipes_view, name="recipes"),
    path('recipes/add_recipe/', add_recipe_view, name='add_recipe'),
    path('recipes/edit_recipe/<int:pk>/', add_recipe_view, name='edit_recipe'),
    path('recipes/api/ingredients/', IngredientSearchView.as_view(), name='ingredient-search'),
    path('recipes/<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipes/like_recipe/', LikeRecipeView.as_view(), name='like_recipe'),
    path('analytics/', analytics_view, name='analytics'),
    path("import/", import_view, name="import"),
    path("stat/", stat_view, name="stat"),
]

web/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Count

User = get_user_model()

class Recipe(models.Model):

    class RecipeManager(models.Manager):
        def detail(self):
            return self.get_queryset() \
                 .prefetch_related('ingredients', 'likes', 'steps')

        def popular(self):
            return self.get_queryset() \
                .annotate(likes_count=Count('likes')) \
                .order_by('-likes_count')


    DIFFICULTY_OPTIONS = (
        ('hard', 'Сложный'),
        ('medium', 'Средней сложности'),
        ('easy', 'Легкий')
    )

    ACCESS_OPTIONS = (
        ('public', 'Общедоступный'),
        ('private', 'Закрытый')
    )

    picture = models.ImageField(upload_to='images/recipes_pictures', blank=True, null=True, verbose_name='Фото')
    title = models.CharField(max_length=255, verbose_name='Название')
    ingredients = models.ManyToManyField('Ingredient', related_name='ingredients')
    description = models.TextField(verbose_name="Описание приготовления")
    difficulty = models.CharField(max_length=50, choices=DIFFICULTY_OPTIONS, verbose_name='Сложность')
    cooking_time = models.IntegerField(verbose_name="Время приготовления")
    author = models.ForeignKey(to=User, verbose_name='Пользователь', on_delete=models.CASCADE)
    access = models.CharField(choices=ACCESS_OPTIONS, default='private', verbose_name='Доступ', max_length=10)

    objects = RecipeManager()

    @property
    def get_sum_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'


class Ingredient(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'


class IngredientQuantity(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, verbose_name='Рецепт')
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, verbose_name='Ингредиент')
    quantity = models.CharField(max_length=50, verbose_name='Количество')

    def __str__(self):
        return f'{self.recipe.title} - {self.ingredient.name}: {self.quantity}'

    class Meta:
        verbose_name = 'Количество ингредиента'
        verbose_name_plural = 'Количества ингредиентов'


class RecipeStep(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, verbose_name='Рецепт', related_name='steps')
    image = models.ImageField(upload_to='images/recipes_pictures/steps', blank=True, null=True, verbose_name='Фото шага')
    description = models.TextField(max_length=3000, verbose_name='Описание шага')
    step_number = models.IntegerField(verbose_name='Номер шага')

    def __str__(self):
        return f'{self.recipe.title}, Шаг приготовления {self.step_number}'

    class Meta:
        verbose_name = 'Шаг приготовления'
        verbose_name_plural = 'Шаги приготовления'


class LikeRecipe(models.Model):
    recipe = models.ForeignKey(to=Recipe, verbose_name='Рецепт', on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(to=User, verbose_name='Пользователь', on_delete=models.CASCADE, blank=True, null=True)
    time_create = models.DateTimeField(verbose_name='Время добавления', auto_now_add=True)

    class Meta:
        unique_together = ('recipe', 'user')
        ordering = ('-time_create',)
        indexes = [models.Index(fields=['-time_create'])]
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранное'

    def __str__(self):
        return f'{self.user.username} - {self.recipe.title}'

web/templates/web/add_recipe.html
{% extends 'web/base.html' %}

{% load static %}

{% block content %}

<h1>Добавление рецепта</h1>

<form id="recipe-form" enctype="multipart/form-data">

    <h4>1. Название рецепта</h4>
    <input type="text" id="recipe_name" name="recipe_name" required>

    <h4>2. Краткое описание</h4>

    <textarea id="recipe_description" name="recipe_description" required></textarea>
    <p style="margin-left: auto; margin-right: 7%; margin-top: 7px; color: rgba(0, 0, 0, 0.70); font-size: 14px;">До 310 символов</p>

    <h4>3. Загрузите обложку рецепта</h4>
    <label for="recipe_image"></label>
    <input id="recipe_image" name="recipe_image" type="file" accept=".png, .jpg, .jpeg" required/>

    <h4>4. Ингредиенты</h4>
    <div class="available-ingredients">
    {% for ingredient in ingredients %}
        {% if forloop.counter < 50 %}
            <button type="button" data-ingredient-id="{{ ingredient.id }}">{{ ingredient.name }}</button>
        {% endif %}
    {% endfor %}
    </div>

    <div class="ingredient-quantity">
            <div><p>Вы выбрали:</p></div>
            <div><p>Укажите количество:</p></div>
    </div>

    <input type="text" id="add-new__ingredient" name="add-new__ingredient" placeholder="Дополнительные ингредиенты, например “Соль по вкусу”">

    <h4>5. Шаги приготовления</h4>
    <div id="steps-section">
        <div id="added-steps"></div>
        <h3>+</h3>
    </div>

    <h4>6. Оцените сложность и время приготовления</h4>
    <label for="difficulty">Сложность</label>
    <select id="difficulty" name="difficulty">
        <option value="Легко">Легко</option>
        <option value="Средняя">Средне</option>
        <option value="Сложно">Сложно</option>
    </select>

    <label for="cooking_time">Время приготовления</label>
    <input type="number" name="cooking_time" id="cooking_time" required>

    <br><br>
    <button type="submit">Сохранить в избранном</button>
    <p>Рецепт будете видеть только Вы во вкладке «Избранное»</p>

    <button type="submit" id="save-recipe">Сохранить рецепт</button>
    <p>После модерации Ваш рецепт будет опубликован!</p>


</form>

<script src="{% static 'web/js/add_recipe.js' %}"></script>

{% endblock content %}

web/templates/web/add_recipe_test.html
{% extends 'web/base.html' %}

{% load static %}

{% block content %}

    <h1>Добавление рецепта</h1>

    <form id="recipe-form" enctype="multipart/form-data">
        {% csrf_token %}

        <h4>1. Название рецепта</h4>
        <input type="text" id="recipe_name" name="recipe_name" value="{{ recipe.title }}" required>

        <h4>2. Краткое описание</h4>

        <textarea id="recipe_description" name="recipe_description" required>{{ recipe.title }}</textarea>
        <p style="margin-left: auto; margin-right: 7%; margin-top: 7px; color: rgba(0, 0, 0, 0.70); font-size: 14px;">До 310 символов</p>

        <h4>3. Загрузите обложку рецепта</h4>
        <label for="recipe_image"></label>
        <input id="recipe_image" name="recipe_image" type="file" accept=".png, .jpg, .jpeg" value="{% if recipe != null %}{% if recipe.picture.url != null %}{{ recipe.picture.url }}{% endif %}{% endif %}" required/>

        <h4>4. Ингредиенты</h4>
        <input type="text" id="ingredient-search" name="ingredient_search" placeholder="Введите название ингридиента">
        <div class="available-ingredients">
            <label>Ингредиенты:</label>
            <div id="ingredient-buttons" style="display: inline"></div>
            {% for ingredient in ingredients %}
                <button type="button" class="ingredient-button ingredients-on-page" data-ingredient-id="{{ ingredient.id }}">{{ ingredient.name }}</button>
            {% endfor %}
        </div>

        <div class="ingredients_quantity__container">
            <div class="ingredients_quantity__container-title">
                <h5>Количесвта ингредиентов:</h5>
            </div>
            <div class="ingredient-quantity-column">
                <div class="ingredient-quantity">
                    {% if recipe != null %}
                        {% for item in quantity_ingr %}
                            <button type="button" class="ingredient-button selected ingr_edit" data-ingredient-id="{{ item.ingredient.id }}">{{ item.ingredient.name }}</button>
                            <div>
                                <input data-quantity="{{ item.ingredient.id }}" name="quantity_{{ item.ingredient.id }}" placeholder="Количество" value="{{ item.quantity }}">
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>

        <h4>5. Шаги приготовления</h4>
        <div id="steps-section">
            <div id="added-steps">
                {% if recipe != null %}
                    {% if steps != null %}
                        {% for step in steps %}
                            <div class="step">
                                <input type="file" name="step_image_{{ step.step_number }}" accept=".png, .jpg, .jpeg" id="step-image-{{ step.step_number }}" value="{% if step.image.url != null %} {{ step.image.url }} {% endif %}">
                                <textarea name="step_description_{{ step.step_number }}" placeholder="Описание шага" id="step-description-{{ step.step_number }}">{{ step.description }}</textarea>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </div>
            <button type="button" id="add-step">Добавить шаг</button>

        </div>

        <h4>6. Краткое описание</h4>
        <div id="instruction-summary">
            <ol id="summary-list"></ol>
        </div>

        <h4>7. Оцените сложность и время приготовления</h4>
        <select name="difficulty" id="difficulty">
            <option value="easy" {% if recipe != null %}{% if recipe.difficulty == 'easy' %}selected{% endif %}{% endif %}>Легко</option>
            <option value="medium" {% if recipe != null %}{% if recipe.difficulty == 'medium' %}selected{% endif %}{% endif %}>Средне</option>
            <option value="hard" {% if recipe != null %}{% if recipe.difficulty == 'hard' %}selected{% endif %}{% endif %}>Сложно</option>
        </select>

        <label for="cooking_time">Время приготовления (в минутах):</label>
        <input type="number" name="cooking_time" id="cooking_time" value="{{ recipe.cooking_time }}" required>


        <br><br><br>
        <button>Сохранить в избранном</button>
        <p>Рецепт будете видеть только Вы во вкладке «Избранное»</p>

        <button type="button" id="save-recipe" data-url="{{ url }}">Сохранить рецепт</button>
        <p>После модерации Ваш рецепт будет опубликован!</p>



    </form>
<script type=text/javascript>
    var link = "{% url 'recipes' %}"
</script>
<script src="{% static 'web/js/add_recipe.js' %}"></script>

{% endblock content %}

web/templates/web/analytics.html
{% extends 'web/base.html' %}

{% block content %}

    <h1>Аналитика</h1>

    <p>Всего рецептов: <b>{{ overall_stat.count }}</b></p>
    <p>Максимальное время приготовления: {{ overall_stat.max_cooking_time }}</p>
    <p>Минимальное время приготовления: {{ overall_stat.min_cooking_time }}</p>

    <h3>Статистика по ингредиентам</h3>
    {% for ingredient_stat in ingredients_stat %}
        <p>{{ ingredient_stat }} - Использовался раз в рецептах: {{ ingredient_stat.count }}</p>
    {% endfor %}

{% endblock content %}

web/templates/web/auth.html
{% extends 'web/base.html' %}

{% block content %}
    <h1>Авторизация</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Войти</button>
    </form>
{% endblock content %}

web/templates/web/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Recipes Site</title>
</head>
<body>
    <a href="{% url 'home' %}"><h1>Recipes Site</h1></a>
    <nav>
        <a href="{% url 'home' %}">Главная</a>
        <a href="{% url 'recipes' %}">Все рецепты</a>
        {% if user.is_authenticated %}
            <a href="{% url 'add_recipe' %}">Добавить рецепт</a>
            <a href="{% url 'analytics' %}">Аналитика</a>
            <a href="{% url 'import' %}">Импорт</a>
            <a href="{% url 'stat' %}">Статистика</a>
            <div style="text-align: right;">
                Вы авторизированы как <b>{{ user.username }}</b>
                <a href="{% url 'sign_out' %}">Выход</a>
            </div>
        {% else %}
            <div style="text-align: right;">
                <a href="{% url 'sign_up' %}">Регистрация</a>
                <a href="{% url 'sign_in' %}">Авторизация</a>
            </div>
        {% endif %}
    </nav>
    <hr>
    {% block content %}{% endblock %}

</body>
</html>

web/templates/web/home.html
{% extends 'web/base.html' %}

{% load static %}

{% block content %}

    {% include 'web/recipes_filters.html' %}

    {% for recipe in recipes %}
        {% include 'web/recipe_card.html' %}
    {% endfor %}

    всего записей: {{ total_count }}. {{ recipes|length }} на этой странице.

    <nav>
        {% if recipes.has_previous %}
            <a href="?page=1">в начало</a>
            <a href="?page={{ recipes.previous_page_number }}">предыдущая страница</a>
        {% endif %}

        страница {{ recipes.number }} из {{ recipes.paginator.num_pages }}

        {% if recipes.has_next %}
            <a href="?page={{ recipes.next_page_number }}">следующая страница</a>
            <a href="?page={{ recipes.paginator.num_pages }}">в конец</a>
        {% endif %}
    </nav>

    <script src="{% static 'web/js/like.js' %}"></script>

{% endblock content %}

web/templates/web/import.html
{% extends 'web/base.html' %}

{% block content %}

    <h2>Импорт из CSV файла</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Импортировать</button>
    </form>

{% endblock content %}

web/templates/web/recipe_card.html
{% if recipe.picture.url is not null %}
    <img src="{{ recipe.picture.url }}" alt="{{ recipe.title }}" style="height:100px;"/>
{% endif %}
<a href="{% url 'recipe_detail' recipe.pk %}"><h3>{{ recipe.title }}</h3></a>
<p>{{ recipe.description }}</p>
<p>Сложность: {{ recipe.get_difficulty_display }}</p>
<p>Время приготовления: {{ recipe.cooking_time }}</p>
<small>
    {% if recipe.ingredients.all %}
        Ингредиенты:
        {% for ingredient in recipe.ingredients.all %}
            {{ ingredient.name }}
        {% endfor %}
    {% endif %}
</small>
<br><br>
<button class="like-button" style="{% if likes %}{% if recipe.id in likes %}border-color: #f44336;{% endif %}{% endif %}cursor: pointer;" data-recipe="{{ recipe.id }}">Likes: {{ recipe.get_sum_likes }}</button>
{% if recipe.author == user %}
    <br><br>
    <a href="{% url 'edit_recipe' recipe.pk %}">Изменить</a>
{% endif %}
<hr>

web/templates/web/recipe_detail.html
{% extends 'web/base.html' %}

{% load static %}

{% block content %}
    {% if recipe.picture.url is not null %}
        <img src="{{ recipe.picture.url }}" alt="{{ recipe.title }}" style="height:250px;"/>
    {% endif %}
    <h1>{{ recipe.title }}</h1>
    <h3>Сложность: {{ recipe.get_difficulty_display }}</h3>
    <h3>Время приготовления: {{ recipe.cooking_time }}</h3>
    <button class="like-button" style="{% if likes %}{% if recipe.id in likes %}border-color: #f44336;{% endif %}{% endif %}cursor: pointer;" data-recipe="{{ recipe.id }}">Likes: {{ recipe.get_sum_likes }}</button>
    <p>{{ recipe.description }}</p>

    <h2>Ингредиенты:</h2>
    <ul class="ingredients__list ingredients-list">
        {% for quantity in quantity_ingr %}
            <li>- {{ quantity.ingredient.name}}: {{quantity.quantity }}</li>
        {% endfor %}
    </ul>

    <h2>Пошаговый рецепт</h2>

    {% for step in steps %}
        <div>
            {% if step.image.url is not null %}
                <img src="{{ step.image.url }}" alt="" style="height:100px;">
            {% endif %}
            <h3 style="display: inline; text-align: center">{{ step.step_number }} шаг:
                {{ step.description }}</h3>
        </div>
    {% endfor %}

    <script src="{% static 'web/js/like.js' %}"></script>

{% endblock content %}

web/templates/web/recipes_filters.html
<form action="">
    <b>Фильтры:</b><br>

    {% for field in filter_form %}
        {{ field.label }}
        {{ field }}
    {% endfor %}

    <button>Найти</button>
    <button name="export" value="csv">Экспорт в csv</button>

    <a href="?">Показать все</a>
</form>

web/templates/web/recipes_list.html
{% extends 'web/base.html' %}

{% load static %}

{% block content %}

    <h1>Рецепты</h1>

    {% include 'web/recipes_filters.html' %}

    {% for recipe in recipes %}
        {% include 'web/recipe_card.html' %}
    {% endfor %}

    всего записей: {{ total_count }}. {{ recipes|length }} на этой странице.

    <nav>
        {% if recipes.has_previous %}
            <a href="?page=1">в начало</a>
            <a href="?page={{ recipes.previous_page_number }}">предыдущая страница</a>
        {% endif %}

        страница {{ recipes.number }} из {{ recipes.paginator.num_pages }}

        {% if recipes.has_next %}
            <a href="?page={{ recipes.next_page_number }}">следующая страница</a>
            <a href="?page={{ recipes.paginator.num_pages }}">в конец</a>
        {% endif %}
    </nav>


    <script src="{% static 'web/js/like.js' %}"></script>

{% endblock content %}

web/templates/web/registration.html
{% extends 'web/base.html' %}

{% block content %}
    <h1>Регистрация</h1>
    {% if is_success %}
        <p><b>Спасибо за регистрацию</b></p>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Зарегистрироваться</button>
        </form>
    {% endif %}
{% endblock content %}

web/templates/web/stat.html
{% extends 'web/base.html' %}

{% block content %}

    <h2>Статистика</h2>
    <ul>
        {% for url, count in results %}
            <li>
                <b>{{ url }}</b> - {{ count }}
            </li>
        {% endfor %}
    </ul>

{% endblock content %}